name: Latest blog post workflow

on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "POST-LIST"
          feed_list: "https://lostfocus.de/feed/,https://dominikschwind.com/links/feed,https://dominik.photos/feed,https://github.com/lostfocus.atom"
          max_post_count: 10